# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: waka.mailer::sendbox.form_name

# Model Form Field configuration
form: $/waka/mailer/models/sendbox/fields.yaml

# Model Class name
modelClass: Waka\Mailer\Models\SendBox

# Default redirect location
defaultRedirect: waka/mailer/sendboxs

# Create page
# create:
#     title: waka.mailer::sendbox.create
#     redirect: waka/mailer/sendboxs/update/:id
#     redirectClose: waka/mailer/sendboxs

# Update page
# update:
#     title: waka.mailer::sendbox.update
#     redirect: waka/mailer/sendboxs/update/:id
#     redirectClose: waka/mailer/sendboxs

# Preview page
preview:
    title: waka.mailer::sendbox.preview_name
