# ===================================
#  Config filter
# ===================================

scopes:
    datasource:
        label: Source de données
        conditions: data_source in (:filtered)
        modelClass: Waka\Mailer\Models\WakaMail
        options: listAllDataSourceToArray
