# ===================================
# Relation Behavior Config
# ===================================

mailLogs:
    label: waka.mailer::wakamail.mailLogs
    manage:
    view:
        list: $/waka/mailer/models/maillog/columns.yaml
        recordUrl: waka/mailer/maillogs/update/:id
        toolbarButtons: false
        showCheckboxes: false
        filter: config_filters_for_mailLogs.yaml
        showSearch: true
        defaultSort:
            column: created_at
            direction: desc

waka_session:
    label: waka.mailer::wakamail.waka_session
    manage:
        form: $/waka/session/models/wakasession/fields.yaml
    view:
        form: $/waka/session/models/wakasession/fields.yaml
        toolbarButtons: update|delete
        showCheckboxes: false
        defaultSort:
            column: name
            direction: asc

